name: my-ci

# On déclenche le worflow sur tout push
on: [push]

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - uses: docker/build-push-action@v5
        with:
          tags: ci-cd-github:latest
    #  - uses: actions/setup-node@v3
    #  with:
    #    node-version: '14'
    #  - run: npm install -g bats
    #  - run: bats -v