name: my-ci

# On déclenche le worflow sur tout push
on: [push]

jobs:
  buid-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: benoitlorcy/ci-cd-github:latest

    #  - uses: actions/setup-node@v3
    #  with:
    #    node-version: '14'
    #  - run: npm install -g bats
    #  - run: bats -v